name: CI Script to build YaCy Home Page on self-hosted server

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: pip install mkdocs
    - run: mkdocs build
